language: go
sudo: false

env: PATH=$HOME/gopath/bin:$PATH

go:
  - tip
  - 1.6

install:
  - go get github.com/fatih/structs
  - go get gopkg.in/yaml.v2

script: go test -v ./tests/ #default go test -v ./...